global:
  resolve_timeout: 5m
route:
  group_by: ['cluster']
  receiver: 'slack_general'
  routes:
  - match:
      severity: slack
    receiver: slack_general
  - match:
    receiver: slack_general
receivers:
- name: slack_general
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: '#wespeakcloud'
