---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alertmanager-sns-forwarder
  namespace: monitoring
  labels:
    component: alertmanager-sns-forwarder
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: alertmanager-sns-forwarder
      annotations:
        iam.amazonaws.com/role: alertmanager_sns_role
    spec:
      restartPolicy: Always
      containers:
      - name: alertmanager-sns-forwarder
        image: slavayssiere/alertmanager-sns-forwarder:0.1
        imagePullPolicy: Always
        # You can also specify arguments
        # args: ["--addr=:9087", "--debug", "--arn-prefix=arn:aws:sns:${var.region}:{{ environ('ACCOUNT_ID') }}:"]
        env:
          - name: AWS_REGION
            value: "eu-west-1"
          - name: AWS_DEFAULT_REGION
            value: "eu-west-1"
          - name: SNS_FORWARDER_ARN_PREFIX
            value: "arn:aws:sns:eu-west-1:{{ environ('ACCOUNT_ID') }}:sns_topic"
        resources:
          limits:
            memory: 0.3Gi
            cpu: 0.2
          requests:
            cpu: 0.05
            memory: 0.1Gi
        ports:
          - containerPort: 9087
            name: webhook-port
        livenessProbe:
          httpGet:
            path: /health
            port: webhook-port
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: webhook-port
          initialDelaySeconds: 10
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-sns-forwarder-svc
  namespace: monitoring
  labels:
    component:  alertmanager-sns-forwarder
spec:
  ports:
    - port: 9087
      name: webhook-port
  selector:
    component: alertmanager-sns-forwarder

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager-sns-forwarder-metrics-sm
  namespace: monitoring
  labels:
    component: alertmanager-sns-forwarder
    k8s-app: alertmanager-sns-forwarder
spec:
  selector:
    component: alertmanager-sns-forwarder
  endpoints:
  - port: webhook-port
    scrapeTimeout: "30s"
    interval: "40s"